version: '3.7'
services:
    worker:
        build: ScreenshotWorker/.
        environment:
            - SCREENSHOT__MQ__HOST=rabbitmq
            - SCREENSHOT__BROWSER__OUTPUTDIRECTORY=/app/screenshots/
            - SCREENSHOT__BROWSER__PAGEWIDTH=1920
            - SCREENSHOT__BROWSER__PAGEHEIGHT=1080
        volumes:
            - ./screenshots/:/app/screenshots/
        depends_on:
            - rabbitmq
    service:
        build: ScreenshotService/.
        environment:
            - SCREENSHOT__MQ__HOST=rabbitmq
        ports: 
            - "80:80"
        volumes:
            - ./screenshots/:/app/wwwroot/screenshots/
        depends_on:
            - rabbitmq
    rabbitmq:
        image: "rabbitmq:3.7-alpine"

